// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHZyZePN8KGepFQzI5KDXb21tVg8NtcLI',
    appId: '1:1093774391664:web:624e00ca2c6cd74dc6f7b5',
    messagingSenderId: '1093774391664',
    projectId: 'hci202401',
    authDomain: 'hci202401.firebaseapp.com',
    storageBucket: 'hci202401.appspot.com',
    measurementId: 'G-20Q9K1C6CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCIESeVFFAQms_4A1Cp9B_5Wrv-3JhEE0',
    appId: '1:1093774391664:android:c0dab3e8aaa5eb94c6f7b5',
    messagingSenderId: '1093774391664',
    projectId: 'hci202401',
    storageBucket: 'hci202401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlbDw1K9aRsxIG83AMeLjTyo7kOlaEKU',
    appId: '1:1093774391664:ios:d53ec5d4bcdf5832c6f7b5',
    messagingSenderId: '1093774391664',
    projectId: 'hci202401',
    storageBucket: 'hci202401.appspot.com',
    iosBundleId: 'com.gogang.loop.loop',
  );

}