// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiZZvJdI2IKeg5bJEdS3O8pkkJvW6giiA',
    appId: '1:1073104380740:web:2f168dd1e5b80d11fa2d11',
    messagingSenderId: '1073104380740',
    projectId: 'loop-flutter-e3044',
    authDomain: 'loop-flutter-e3044.firebaseapp.com',
    storageBucket: 'loop-flutter-e3044.firebasestorage.app',
    measurementId: 'G-4MDSC3S5MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSair9jjrS5WF25f1DijnMlZnQYd-oR08',
    appId: '1:1073104380740:android:43d426abdcceb429fa2d11',
    messagingSenderId: '1073104380740',
    projectId: 'loop-flutter-e3044',
    storageBucket: 'loop-flutter-e3044.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvuHXy3fmlm0jVjOHi7YpBGsL4kSpIyFA',
    appId: '1:1073104380740:ios:43f8f684f6e1c670fa2d11',
    messagingSenderId: '1073104380740',
    projectId: 'loop-flutter-e3044',
    storageBucket: 'loop-flutter-e3044.firebasestorage.app',
    iosBundleId: 'com.gogang.loop.loop',
  );
}
